// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZ1jq5dvMILFFzdY3B3szc_5ioR_oyOo',
    appId: '1:619194274838:android:bbaca60fc59f484a7a1137',
    messagingSenderId: '619194274838',
    projectId: 'the-secret-of-better-health',
    databaseURL: 'https://the-secret-of-better-health-default-rtdb.firebaseio.com',
    storageBucket: 'the-secret-of-better-health.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcnKiocuPznypcpR71Pn0AQKZCb5aPw2M',
    appId: '1:619194274838:ios:a3854a1f4085b7157a1137',
    messagingSenderId: '619194274838',
    projectId: 'the-secret-of-better-health',
    databaseURL: 'https://the-secret-of-better-health-default-rtdb.firebaseio.com',
    storageBucket: 'the-secret-of-better-health.appspot.com',
    iosClientId: '619194274838-eo09m3u21vvavvui0hvvj0atid43jktm.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
